### ISSUE TITLE
对3.4.kehou-1添加关于“可能是其他答案”的提示

### ISSUE THREAD

**Issue by CA-TT-AC** [gaobobo/EduCoder_OperationSys#27]
https://github.com/gaobobo/EduCoder_OperationSys/blob/main/Source/3.4.kehou-1/%E7%AC%AC%E4%B8%89%E5%85%B3.txt 中，

第四问答案错误，

“4.0 号进程是在执行哪一条指令时切换到 1 号进程的？(0x8:0x06f33)当 0 号进程后来恢复运行时，是从哪一条指令开始执行的？(0x6f37)”

应为

“4.0 号进程是在执行哪一条指令时切换到 1 号进程的？(0x06f33)当 0 号进程后来恢复运行时，是从哪一条指令开始执行的？(0x6f37)”

**Comment by gaobobo** [comment]
实际上该题的正确答案应该是`0x6f33`、`0x6f37`（都不对齐到32位）或`0x00006f33`、`0x00006f37`（都对齐到32位）。

但是网上对该题答案不一致，可能是部分学校发现了这个问题然后修改了答案或者头歌的版本不一致导致的答案不一致。

目前该答案在本人所就读的学校的头歌上评测是正确的，因此该issue不会归入bug而是enhancement。

后续会考虑在脚本中加入提示说明。

**Comment by CA-TT-AC** [comment]
收到，感谢你的回复！


ps 这真是一个很有用的项目👍🏻

--------------原始邮件--------------
发件人："Bobby&nbsp;Gao ***@***.***&gt;;
发送时间：2024年5月4日(星期六) 下午5:05
收件人："gaobobo/EduCoder_OperationSys" ***@***.***&gt;;
抄送："徐敬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [gaobobo/EduCoder_OperationSys] 替换文件中的错误 (Issue #27)
-----------------------------------

 

 
实际上该题的正确答案应该是0x6f33、0x6f37（都不对齐到32位）或0x00006f33、0x00006f37（都对齐到32位）。
 
但是网上对该题答案不一致，可能是部分学校发现了这个问题然后修改了答案或者头歌的版本不一致导致的答案不一致。
 
目前该答案在本人所就读的学校的头歌上评测是正确的，因此该issue不会归入bug而是enhancement。
 
后续会考虑在脚本中加入提示说明。
